'use client';

import {useMemo,useState} from 'react';
import {calculateCashWaitPlan,calculateScenario,calculateStressScenario,validateScenario,type Scenario} from '@/lib/financeEngine';

const money=(n:number|null|undefined)=>n==null||!Number.isFinite(n)?'N/A':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
const num=(n:number)=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:0}).format(n);
const mo=(n:number|null)=>n===null?'N/A':`${n.toFixed(1)} mo`;
const pct=(n:number|null)=>n===null?'N/A':`${(n*100).toFixed(1)}%`;
const parseMoney=(s:string)=>Number(s.replace(/[^0-9.]/g,''))||0;

const initial:Scenario={purchasePrice:149900,monthlyTakeHome:140000,incomeMode:'regular',conservativeIncome:110000,essentials:60000,debtPayments:15000,plannedMonthlySaving:10000,emergencySavings:300000,availableSavings:200000,reserveTargetMonths:6,paymentMode:'cash',downPayment:30000,upfrontFees:2000,financedFees:0,apr:12,termMonths:12,monthlyPurchaseSaving:25000,emergencyModeExpenses:50000,ownershipMonths:24,accessories:0,maintenance:0,recurringOwnershipCosts:0,expectedResaleValue:0,usesPerWeek:2};

function MoneyInput({value,onChange}:{value:number,onChange:(n:number)=>void}){return <div className="moneyInput"><span>₹</span><input inputMode="decimal" value={num(value)} onChange={e=>onChange(parseMoney(e.target.value))}/></div>}
function Row({label,value,note}:{label:string,value:string,note?:string}){return <div className="dataRow"><span>{label}{note&&<small>{note}</small>}</span><b>{value}</b></div>}

export default function AffordabilityApp(){
  const[v,setV]=useState<Scenario>(initial);
  const[purchaseName,setPurchaseName]=useState('MacBook Pro');
  const[showResult,setShowResult]=useState(false);
  const[wait,setWait]=useState(3);
  const[stressMonths,setStressMonths]=useState(3);
  const[deepPanel,setDeepPanel]=useState<'flex'|'stress'|'ownership'>('flex');
  const[showOwnershipCosts,setShowOwnershipCosts]=useState(false);
  const[saved,setSaved]=useState(false);
  const set=<K extends keyof Scenario>(k:K,x:Scenario[K])=>setV(s=>({...s,[k]:x}));

  const cashScenario=useMemo(()=>({...v,paymentMode:'cash' as const,ownershipMonths:undefined}),[v]);
  const emiScenario=useMemo(()=>({...v,paymentMode:'emi' as const,ownershipMonths:undefined}),[v]);
  const coreErrors=useMemo(()=>validateScenario(cashScenario),[cashScenario]);
  const cashR=useMemo(()=>coreErrors.length?null:calculateScenario(cashScenario),[cashScenario,coreErrors.length]);
  const emiErrors=useMemo(()=>validateScenario(emiScenario),[emiScenario]);
  const emiR=useMemo(()=>emiErrors.length?null:calculateScenario(emiScenario),[emiScenario,emiErrors.length]);
  const waitPlan=useMemo(()=>calculateCashWaitPlan(cashScenario),[cashScenario]);
  const totalBefore=v.availableSavings+v.emergencySavings;
  const waitAvailable=v.availableSavings+Math.max(0,v.monthlyPurchaseSaving)*wait;
  const stress=cashR?calculateStressScenario(cashR,v.emergencyModeExpenses??v.essentials,v.debtPayments,stressMonths):null;
  const ownershipScenario=useMemo(()=>({...cashScenario,ownershipMonths:v.ownershipMonths,accessories:v.accessories,maintenance:v.maintenance,recurringOwnershipCosts:v.recurringOwnershipCosts,expectedResaleValue:v.expectedResaleValue,usesPerWeek:v.usesPerWeek}),[cashScenario,v.ownershipMonths,v.accessories,v.maintenance,v.recurringOwnershipCosts,v.expectedResaleValue,v.usesPerWeek]);
  const ownershipErrors=useMemo(()=>validateScenario(ownershipScenario),[ownershipScenario]);
  const ownershipR=useMemo(()=>ownershipErrors.length?null:calculateScenario(ownershipScenario),[ownershipScenario,ownershipErrors.length]);
  const cashShortfall=Math.max(0,v.purchasePrice-totalBefore);

  const save=()=>{localStorage.setItem('cai-scenario',JSON.stringify({scenario:v,purchaseName}));setSaved(true);setTimeout(()=>setSaved(false),1500)};
  const load=()=>{const raw=localStorage.getItem('cai-scenario');if(!raw)return;try{const p=JSON.parse(raw);if(p?.scenario){setV(p.scenario);setPurchaseName(p.purchaseName??'')}else setV(p)}catch{}};
  const MI=({k}:{k:keyof Scenario})=><MoneyInput value={Number(v[k]??0)} onChange={n=>set(k,n as never)}/>;

  return <main className="appShell">
    <nav className="nav"><div className="brand"><div className="brandMark">₹</div><div><b>BeforeYouBuy</b><small>See what changes before you decide</small></div></div><details className="moreMenu"><summary aria-label="Scenario options">•••</summary><div><button onClick={save}>{saved?'Saved ✓':'Save on this device'}</button><button onClick={load}>Load saved scenario</button></div></details></nav>

    {!showResult&&<><section className="intro"><div className="eyebrow">PRIVATE • LOCAL • NO ACCOUNT</div><h1>Can I afford it?</h1><p>Six numbers. One clear view of what this purchase changes.</p></section><section className="questionCard"><div className="stepHeader"><span>01</span><div><h2>What are you thinking of buying?</h2><p>Start with the purchase.</p></div></div><label className="field bigField">Purchase name<input value={purchaseName} onChange={e=>setPurchaseName(e.target.value)} placeholder="e.g. MacBook Pro"/></label><label className="field bigField">Purchase price<MI k="purchasePrice"/></label><div className="divider"/><div className="stepHeader"><span>02</span><div><h2>Your monthly money</h2><p>Take-home income and required commitments.</p></div></div><div className="formGrid"><label className="field">Monthly take-home<MI k="monthlyTakeHome"/></label><label className="field">Essential + mandatory expenses<MI k="essentials"/></label><label className="field">Existing debt payments<MI k="debtPayments"/></label></div><div className="divider"/><div className="stepHeader"><span>03</span><div><h2>Your cash</h2><p>Separate protected money from purchase-ready money.</p></div></div><div className="formGrid twoCols"><label className="field">Emergency savings<MI k="emergencySavings"/><small>Money you intend to protect for unexpected needs.</small></label><label className="field">Available savings<MI k="availableSavings"/><small>Liquid money you could reasonably use now.</small></label></div><details className="preResultAdvanced"><summary>Reserve target · {v.reserveTargetMonths} months</summary><label className="field"><input type="range" min="1" max="18" value={v.reserveTargetMonths} onChange={e=>set('reserveTargetMonths',+e.target.value)}/><small>6 months is a common reference point, not a universal rule.</small></label></details>{coreErrors.length>0&&<div className="validationBox">{coreErrors.map(x=><div key={x}>• {x}</div>)}</div>}<button className="primaryCta" disabled={coreErrors.length>0} onClick={()=>{setShowResult(true);window.scrollTo({top:0,behavior:'smooth'})}}>See the impact <span>→</span></button><p className="privacyLine">Calculated locally. Nothing is stored unless you choose Save.</p></section></>}

    {showResult&&cashR&&<><section className="resultTop"><button className="backButton" onClick={()=>setShowResult(false)}>← Edit numbers</button><div className="purchaseContext"><span>{purchaseName||'This purchase'}</span><strong>{money(v.purchasePrice)}</strong></div></section>

    {cashR.cashState==='insufficient_liquid_cash'?<section className="impactHero unavailable"><div className="eyebrow">CASH PURCHASE</div><h1>Current liquid cash is insufficient</h1><p>You have {money(totalBefore)} in current liquid savings against a {money(v.purchasePrice)} purchase.</p><div className="shortfallHero"><span>Cash shortfall</span><strong>{money(cashShortfall)}</strong></div><div className="fundingFact warn">Cash purchase is not fully fundable from current liquid savings.</div></section>:<section className="impactHero"><div className="eyebrow">AFTER THIS PURCHASE</div><div className="heroRunway"><strong>{cashR.liquidRunwayAfter===null?'—':cashR.liquidRunwayAfter.toFixed(1)}</strong><span>months of liquid runway remain</span></div><div className="runwayJourney"><span>{mo(cashR.totalLiquidRunway)} before</span><i>→</i><b>{mo(cashR.liquidRunwayAfter)} after</b></div><div className={`targetLine ${cashR.reserveGap>0?'warn':''}`}><span>Target {v.reserveTargetMonths} months</span><b>{cashR.reserveGap===0?'Target preserved':`Short by ${money(cashR.reserveGap)}`}</b></div><div className={`fundingFact ${cashR.emergencyUsed===0?'ok':'warn'}`}>{cashR.emergencyUsed===0?'✓ No emergency savings used':`△ ${money(cashR.emergencyUsed)} of emergency savings used`}</div></section>}

    <section className="beforeAfter">{cashR.cashState==='insufficient_liquid_cash'?<><div className="baHead"><span>Cash position</span><b>Amount</b><strong>Status</strong></div><div><span>Purchase price</span><b>{money(v.purchasePrice)}</b><strong>Needed</strong></div><div><span>Liquid cash now</span><b>{money(totalBefore)}</b><strong>Available</strong></div><div><span>Cash shortfall</span><b>{money(cashShortfall)}</b><strong>Unfunded</strong></div><div><span>Current runway</span><b>{mo(cashR.totalLiquidRunway)}</b><strong>Before purchase</strong></div></>:<><div className="baHead"><span>What changes</span><b>Before</b><strong>After</strong></div><div><span>Liquid savings</span><b>{money(totalBefore)}</b><strong>{money(cashR.liquidAfter)}</strong></div><div><span>Liquid runway</span><b>{mo(cashR.totalLiquidRunway)}</b><strong>{mo(cashR.liquidRunwayAfter)}</strong></div><div><span>Monthly free cash</span><b>{money(cashR.cashBuffer)}</b><strong>{money(cashR.cashBufferAfter)}</strong></div>{cashR.cashBuffer===cashR.cashBufferAfter&&<p className="tableNote">Monthly free cash does not change because the main scenario is a cash purchase.</p>}</>}</section>

    <div className="exploreHeading"><div><span>OPTIONAL</span><h2>Test the decision</h2></div><p>Explore alternatives without changing your original numbers.</p></div><section className="accordionStack grouped">

    <details className="detailAccordion"><summary><div><span>01 · Payment</span><b>Cash or EMI?</b><small>Compare liquidity, monthly pressure and total cost</small></div><em>+</em></summary><div className="accordionBody"><div className="comparisonGrid"><article><div className="compareTitle"><span>Cash</span><b>{cashR.cashState==='insufficient_liquid_cash'?'Not fully fundable':'Current option'}</b></div><Row label="Pay now" value={money(v.purchasePrice)}/><Row label="Liquid savings after" value={cashR.cashState==='insufficient_liquid_cash'?'N/A':money(cashR.liquidAfter)}/><Row label="Runway after" value={cashR.cashState==='insufficient_liquid_cash'?'N/A':mo(cashR.liquidRunwayAfter)}/><Row label="Emergency savings used" value={money(cashR.emergencyUsed)}/></article><article><div className="compareTitle"><span>EMI</span><b>Alternative</b></div>{emiR?<><Row label="Pay now" value={money(v.downPayment+v.upfrontFees)}/><Row label="New EMI" value={`${money(emiR.newEmi)}/mo`}/><Row label="Monthly free cash" value={money(emiR.cashBufferAfter)}/><Row label="Total paid" value={money(emiR.totalFinancingCost)}/><Row label="Extra vs cash price" value={money(emiR.financingPremium)}/></>:<p className="note">Complete valid EMI terms below.</p>}</article></div><details className="inlineAdvanced"><summary>Adjust EMI assumptions</summary><div className="formGrid twoCols"><label className="field">Down payment<MI k="downPayment"/></label><label className="field">Upfront fees<MI k="upfrontFees"/></label><label className="field">Financed fees<MI k="financedFees"/></label><label className="field">Term (months)<input type="number" min="1" value={v.termMonths} onChange={e=>set('termMonths',+e.target.value)}/></label><label className="field">APR %<input type="number" min="0" step="0.1" value={v.apr} onChange={e=>set('apr',+e.target.value)}/></label></div>{emiErrors.length>0&&<div className="validationBox">{emiErrors.map(x=><div key={x}>• {x}</div>)}</div>}{emiR&&<div className="rows compact"><Row label="Debt share of take-home" value={pct(emiR.debtShareTakeHome)}/><Row label="Initial liquid runway with EMI" value={mo(emiR.liquidRunwayAfter)}/></div>}</details></div></details>

    <details className="detailAccordion"><summary><div><span>02 · Timing & target</span><b>When would it fit your target?</b><small>Make the target answer primary, then test other dates</small></div><em>+</em></summary><div className="accordionBody"><div className="targetAnswer"><span>At {money(v.monthlyPurchaseSaving)}/month</span><strong>{waitPlan.earliestViableMonth===null?'No target date yet':waitPlan.earliestViableMonth===0?'It already fits':`About ${waitPlan.earliestViableMonth} months`}</strong><p>{waitPlan.earliestViableMonth===null?'Set a positive monthly purchase-saving amount to estimate when both the purchase and selected reserve can fit.':waitPlan.earliestViableMonth===0?'The cash purchase can already be funded while preserving your selected reserve target.':'This is the earliest month that both funds the purchase without emergency savings and preserves your selected reserve target.'}</p></div><label className="field">Monthly purchase saving<MI k="monthlyPurchaseSaving"/></label><div className="quickWait"><span>Test another wait</span><div>{[1,3,6,12].map(x=><button key={x} className={wait===x?'active':''} onClick={()=>setWait(x)}>{x} mo</button>)}</div></div><label className="field">Custom wait · {wait} months<input type="range" min="0" max="36" value={wait} onChange={e=>setWait(+e.target.value)}/></label><div className="callout"><strong>{money(waitAvailable)}</strong><span>available savings after {wait} months, assuming price, income and expenses stay unchanged</span></div><div className="subDivider"/><h3>What would have to change?</h3><div className="solutionList"><Row label="Add liquid savings" value={money(waitPlan.reservePreservationGap)}/><Row label="Wait at your saving rate" value={waitPlan.earliestViableMonth===null?'N/A':`${waitPlan.earliestViableMonth} months`}/><Row label="Reduce the cash price" value={waitPlan.reservePreservationGap<=v.purchasePrice?money(waitPlan.reservePreservationGap):'Price reduction alone is not enough'} /></div>{waitPlan.reservePreservationGap>v.purchasePrice&&<p className="note">Even a zero-price purchase would not by itself restore the selected reserve; additional liquid savings are still required.</p>}</div></details>

    <details className="detailAccordion secondary"><summary><div><span>03 · Deeper analysis</span><b>Flexibility, stress & ownership</b><small>Open one analysis at a time</small></div><em>+</em></summary><div className="accordionBody"><div className="analysisTabs"><button className={deepPanel==='flex'?'active':''} onClick={()=>setDeepPanel('flex')}>Flexibility</button><button className={deepPanel==='stress'?'active':''} onClick={()=>setDeepPanel('stress')}>Income interruption</button><button className={deepPanel==='ownership'?'active':''} onClick={()=>setDeepPanel('ownership')}>Ownership</button></div>
    {deepPanel==='flex'&&<section className="analysisPanel"><h3>Month-to-month flexibility</h3><p className="note">Based on the cash purchase shown in the main result.</p><div className="segmented"><button className={v.incomeMode==='regular'?'active':''} onClick={()=>set('incomeMode','regular')}>Regular income</button><button className={v.incomeMode==='variable'?'active':''} onClick={()=>set('incomeMode','variable')}>Variable income</button></div>{v.incomeMode==='variable'&&<label className="field">Conservative monthly income<MI k="conservativeIncome"/></label>}<label className="field">Planned monthly saving<MI k="plannedMonthlySaving"/></label><div className="rows"><Row label="Income used for analysis" value={money(cashR.analysisIncome)}/><Row label="Cash buffer" value={money(cashR.cashBufferAfter)}/><Row label="After planned saving" value={money(cashR.discretionaryCapacityAfter)}/></div></section>}
    {deepPanel==='stress'&&<section className="analysisPanel"><div className="stressAnswer"><span>If income stopped today</span><strong>{stress?.runwayMonths===null?'N/A':`${stress?.runwayMonths.toFixed(1)} months`}</strong><p>Approximate coverage from post-purchase liquid cash under the emergency-spending assumption below.</p></div><div className="quickWait"><span>Test interruption</span><div>{[1,3,6,12].map(x=><button key={x} className={stressMonths===x?'active':''} onClick={()=>setStressMonths(x)}>{x} mo</button>)}</div></div><Row label={`Liquid cash after ${stressMonths} months`} value={money(stress?.liquidRemaining)}/><details className="inlineAdvanced"><summary>Adjust emergency spending assumption</summary><label className="field">Emergency-mode monthly expenses<MI k="emergencyModeExpenses"/></label><Row label="Stress monthly burn" value={money(stress?.monthlyBurn)}/><p className="note">Existing debt payments are assumed unchanged. The main stress test uses the cash-purchase scenario, so no new EMI is included.</p></details></section>}
    {deepPanel==='ownership'&&<section className="analysisPanel"><h3>Ownership cost</h3><p className="note">Based on the cash purchase shown above. Financing cost is compared separately in Payment.</p><div className="formGrid twoCols"><label className="field">How many months will you keep it?<input type="number" min="1" value={v.ownershipMonths??24} onChange={e=>set('ownershipMonths',+e.target.value)}/></label><label className="field">Uses per week<input type="number" min="0" value={v.usesPerWeek??0} onChange={e=>set('usesPerWeek',+e.target.value)}/></label></div><details className="inlineAdvanced" open={showOwnershipCosts} onToggle={e=>setShowOwnershipCosts(e.currentTarget.open)}><summary>+ Add ownership costs</summary><div className="formGrid twoCols"><label className="field">Accessories<MI k="accessories"/></label><label className="field">Maintenance<MI k="maintenance"/></label><label className="field">Recurring ownership costs (total)<MI k="recurringOwnershipCosts"/></label><label className="field">Expected resale value<MI k="expectedResaleValue"/></label></div></details>{ownershipErrors.length>0?<div className="validationBox">{ownershipErrors.map(x=><div key={x}>• {x}</div>)}</div>:ownershipR?.ownership&&<div className="ownershipResult"><span>Estimated cost over {v.ownershipMonths} months</span><strong>{money(ownershipR.ownership.totalOwnershipCost)}</strong><div className="rows"><Row label="Purchase price" value={money(v.purchasePrice)}/><Row label="Additional ownership costs" value={money((v.accessories??0)+(v.maintenance??0)+(v.recurringOwnershipCosts??0))}/><Row label="Expected resale" value={`− ${money(v.expectedResaleValue??0)}`}/><Row label="Average cost per month" value={money(ownershipR.ownership.costPerMonth)}/><Row label="Average cost per expected use" value={money(ownershipR.ownership.costPerUse)}/></div></div>}</section>}</div></details>
    </section><p className="resultDisclaimer">These are consequences of the numbers and boundaries you entered, not a recommendation to buy or not buy.</p></>}
  </main>;
}
