'use client';

import {useMemo,useState} from 'react';
import {calculateScenario,validateScenario,type Scenario} from '@/lib/financeEngine';

const money=(n:number|null|undefined)=>n==null||!Number.isFinite(n)?'N/A':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
const num=(n:number)=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:0}).format(n);
const months=(n:number|null)=>n===null?'N/A':`${n.toFixed(1)} mo`;
const parseMoney=(s:string)=>Number(s.replace(/[^0-9.]/g,''))||0;
const initial:Scenario={purchasePrice:149900,monthlyTakeHome:140000,incomeMode:'regular',conservativeIncome:110000,essentials:60000,debtPayments:15000,plannedMonthlySaving:10000,emergencySavings:300000,availableSavings:200000,reserveTargetMonths:6,paymentMode:'cash',downPayment:30000,upfrontFees:2000,financedFees:0,apr:12,termMonths:12,monthlyPurchaseSaving:25000,emergencyModeExpenses:50000,ownershipMonths:24,accessories:0,maintenance:0,recurringOwnershipCosts:0,expectedResaleValue:0,usesPerWeek:2};

function MoneyInput({value,onChange}:{value:number,onChange:(n:number)=>void}){return <div className="moneyInput"><span>₹</span><input inputMode="decimal" value={num(value)} onChange={e=>onChange(parseMoney(e.target.value))}/></div>}
function Row({label,value}:{label:string,value:string}){return <div><span>{label}</span><b>{value}</b></div>}

export default function AffordabilityAppV2(){
 const[v,setV]=useState<Scenario>(initial),[purchaseName,setPurchaseName]=useState('MacBook Pro'),[showResult,setShowResult]=useState(false),[wait,setWait]=useState(3),[stress,setStress]=useState(2),[saved,setSaved]=useState(false);
 const set=<K extends keyof Scenario>(k:K,x:Scenario[K])=>setV(s=>({...s,[k]:x}));
 const errors=useMemo(()=>validateScenario(v),[v]);
 const r=useMemo(()=>errors.length?null:calculateScenario(v),[v,errors.length]);
 const totalBefore=v.availableSavings+v.emergencySavings;
 const waitAvailable=v.availableSavings+Math.max(0,v.monthlyPurchaseSaving)*wait;
 const stressBurn=(v.emergencyModeExpenses??v.essentials)+v.debtPayments+(r?.newEmi??0);
 const stressRemaining=r?Math.max(0,r.liquidAfter-stressBurn*stress):null;
 const save=()=>{localStorage.setItem('cai-scenario',JSON.stringify({scenario:v,purchaseName}));setSaved(true);setTimeout(()=>setSaved(false),1400)};
 const load=()=>{const raw=localStorage.getItem('cai-scenario');if(!raw)return;try{const p=JSON.parse(raw);if(p?.scenario){setV(p.scenario);setPurchaseName(p.purchaseName??'')}else setV(p)}catch{}};
 const MI=({k}:{k:keyof Scenario})=><MoneyInput value={Number(v[k]??0)} onChange={n=>set(k,n as never)}/>;
 const targetDelta=r?.liquidRunwayAfter==null?null:r.liquidRunwayAfter-v.reserveTargetMonths;
 const fundingFact=r?.cashState==='fundable_without_emergency'?'No emergency savings used':r?.cashState==='uses_emergency'?`${money(r.emergencyUsed)} from emergency savings`:r?'Current liquid cash is insufficient':'Complete the numbers';

 return <main className="appShell"><nav className="nav"><div className="brand"><div className="brandMark">₹</div><div><b>BeforeYouBuy</b><small>See what changes before you decide</small></div></div><details className="moreMenu"><summary aria-label="Scenario options">•••</summary><div><button onClick={save}>{saved?'Saved ✓':'Save on this device'}</button><button onClick={load}>Load saved scenario</button></div></details></nav>
 {!showResult&&<><section className="intro"><div className="eyebrow">PRIVATE • LOCAL • NO ACCOUNT</div><h1>Can I afford it?</h1><p>Six numbers. One clear view of what this purchase changes.</p></section><section className="questionCard"><div className="stepHeader"><span>01</span><div><h2>What are you thinking of buying?</h2><p>Start with the purchase.</p></div></div><label className="field bigField">Purchase name<input value={purchaseName} onChange={e=>setPurchaseName(e.target.value)} placeholder="e.g. MacBook Pro"/></label><label className="field bigField">Purchase price<MI k="purchasePrice"/></label><div className="divider"/><div className="stepHeader"><span>02</span><div><h2>Your monthly money</h2><p>Take-home income and required commitments.</p></div></div><div className="formGrid"><label className="field">Monthly take-home<MI k="monthlyTakeHome"/></label><label className="field">Essential + mandatory expenses<MI k="essentials"/></label><label className="field">Existing debt payments<MI k="debtPayments"/></label></div><div className="divider"/><div className="stepHeader"><span>03</span><div><h2>Your cash</h2><p>Separate protected money from purchase-ready money.</p></div></div><div className="formGrid twoCols"><label className="field">Emergency savings<MI k="emergencySavings"/><small>Money you intend to protect for unexpected needs.</small></label><label className="field">Available savings<MI k="availableSavings"/><small>Liquid money you could reasonably use now.</small></label></div><details className="preResultAdvanced"><summary>Reserve target · {v.reserveTargetMonths} months</summary><label className="field"><input type="range" min="1" max="18" value={v.reserveTargetMonths} onChange={e=>set('reserveTargetMonths',+e.target.value)}/><small>6 months is a common reference point, not a universal rule.</small></label></details>{errors.length>0&&<div className="validationBox">{errors.map(x=><div key={x}>• {x}</div>)}</div>}<button className="primaryCta" disabled={errors.length>0} onClick={()=>{setShowResult(true);window.scrollTo({top:0,behavior:'smooth'})}}>See the impact <span>→</span></button><p className="privacyLine">Calculated locally. Nothing is stored unless you choose Save.</p></section></>}
 {showResult&&r&&<><section className="resultTop"><button className="backButton" onClick={()=>setShowResult(false)}>← Edit numbers</button><div className="purchaseContext"><span>{purchaseName||'This purchase'}</span><strong>{money(v.purchasePrice)}</strong></div></section>
 <section className="impactHero"><div className="eyebrow">AFTER THIS PURCHASE</div><div className="heroRunway"><strong>{r.liquidRunwayAfter==null?'N/A':r.liquidRunwayAfter.toFixed(1)}</strong><span>months of liquid runway remain</span></div><div className="runwayJourney"><span>{months(r.totalLiquidRunway)} before</span><i>→</i><b>{months(r.liquidRunwayAfter)} after</b></div><div className={`targetStatus ${r.reserveGap===0?'ok':'warn'}`}><div><span>Your target</span><b>{v.reserveTargetMonths} months</b></div><div><span>{r.reserveGap===0?'Target preserved':'Gap to target'}</span><b>{r.reserveGap===0?'None':money(r.reserveGap)}</b></div></div><div className={`fundingFact ${r.cashState==='fundable_without_emergency'?'ok':''}`}>✓ {fundingFact}</div></section>
 <section className="beforeAfter"><div className="baHead"><span>What changes</span><b>Before</b><b>After</b></div><div><span>Liquid savings</span><b>{money(totalBefore)}</b><strong>{money(r.liquidAfter)}</strong></div><div><span>Liquid runway</span><b>{months(r.totalLiquidRunway)}</b><strong>{months(r.liquidRunwayAfter)}</strong></div><div><span>Monthly free cash</span><b>{money(r.cashBuffer)}</b><strong>{money(r.cashBufferAfter)}</strong></div></section>
 {r.reserveGap>0&&<p className="coreInsight"><b>{money(r.reserveGap)} short</b> of the liquid reserve needed for your selected {v.reserveTargetMonths}-month target.</p>}
 <div className="exploreHeading"><div><span>OPTIONAL</span><h2>Test the decision</h2></div><p>Explore alternatives without changing your original numbers.</p></div><section className="accordionStack grouped">
 <details className="detailAccordion"><summary><div><span>01 · Payment</span><b>Cash, reserve & financing</b><small>Where the money comes from and what EMI changes</small></div><em>+</em></summary><div className="accordionBody"><h3>Cash breakdown</h3><div className="rows"><Row label="Available savings used" value={money(r.availableUsed)}/><Row label="Emergency savings used" value={money(r.emergencyUsed)}/><Row label="Available savings after" value={money(r.availableAfter)}/><Row label="Emergency savings after" value={money(r.emergencyAfter)}/><Row label="Dedicated emergency runway" value={months(r.dedicatedEmergencyRunway)}/></div><div className="subDivider"/><h3>Compare payment method</h3><div className="segmented"><button className={v.paymentMode==='cash'?'active':''} onClick={()=>set('paymentMode','cash')}>Cash</button><button className={v.paymentMode==='emi'?'active':''} onClick={()=>set('paymentMode','emi')}>EMI</button></div>{v.paymentMode==='emi'&&<><div className="formGrid twoCols"><label className="field">Down payment<MI k="downPayment"/></label><label className="field">Upfront fees<MI k="upfrontFees"/></label><label className="field">Financed fees<MI k="financedFees"/></label><label className="field">Term (months)<input type="number" min="1" value={v.termMonths} onChange={e=>set('termMonths',+e.target.value)}/></label><label className="field">APR %<input type="number" min="0" step="0.1" value={v.apr} onChange={e=>set('apr',+e.target.value)}/></label></div><div className="rows"><Row label="New EMI" value={`${money(r.newEmi)}/mo`}/><Row label="Total financing cost" value={money(r.totalFinancingCost)}/><Row label="Extra paid vs cash" value={money(r.financingPremium)}/></div></>}</div></details>
 <details className="detailAccordion"><summary><div><span>02 · Timing & target</span><b>Wait or change the purchase</b><small>See what time, savings or price would change</small></div><em>+</em></summary><div className="accordionBody"><h3>What if I wait?</h3><div className="formGrid twoCols"><label className="field">Monthly purchase saving<MI k="monthlyPurchaseSaving"/></label><label className="field">Wait · {wait} months<input type="range" min="0" max="36" value={wait} onChange={e=>setWait(+e.target.value)}/></label></div><div className="callout"><strong>{money(waitAvailable)}</strong><span>available savings after {wait} months</span></div><p className="note">Price, income and expenses are assumed unchanged. {r.reserveGap===0?'Your target is already preserved.':r.monthsToCloseReserveGap===null?'Set a positive monthly saving amount to estimate timing.':`About ${r.monthsToCloseReserveGap} months would close the current reserve gap.`}</p><div className="subDivider"/><div className="rows"><Row label="Purchase-ready cash without emergency savings" value={money(r.purchaseReadyCash)}/><Row label="Cash while preserving selected reserve" value={money(r.cashWhilePreservingTarget)}/><Row label="Additional liquid savings required" value={money(r.reserveGap)}/></div></div></details>
 <details className="detailAccordion secondary"><summary><div><span>03 · Deeper analysis</span><b>Flexibility, stress & ownership</b><small>For significant or long-lived purchases</small></div><em>+</em></summary><div className="accordionBody"><h3>Monthly flexibility</h3><div className="segmented"><button className={v.incomeMode==='regular'?'active':''} onClick={()=>set('incomeMode','regular')}>Regular income</button><button className={v.incomeMode==='variable'?'active':''} onClick={()=>set('incomeMode','variable')}>Variable income</button></div>{v.incomeMode==='variable'&&<label className="field">Conservative monthly income<MI k="conservativeIncome"/></label>}<label className="field">Planned monthly saving<MI k="plannedMonthlySaving"/></label><div className="rows"><Row label="Income used for analysis" value={money(r.analysisIncome)}/><Row label="Cash buffer" value={`${money(r.cashBuffer)} → ${money(r.cashBufferAfter)}`}/><Row label="After planned saving" value={`${money(r.discretionaryCapacity)} → ${money(r.discretionaryCapacityAfter)}`}/></div><div className="subDivider"/><h3>Stress test</h3><div className="formGrid twoCols"><label className="field">Emergency-mode expenses<MI k="emergencyModeExpenses"/></label><label className="field">Interruption · {stress} months<input type="range" min="0" max="12" value={stress} onChange={e=>setStress(+e.target.value)}/></label></div><div className="rows"><Row label="Stress monthly burn" value={money(stressBurn)}/><Row label={`Liquid cash after ${stress} months`} value={money(stressRemaining)}/></div><div className="subDivider"/><h3>Ownership cost</h3><div className="formGrid twoCols"><label className="field">Ownership months<input type="number" min="1" value={v.ownershipMonths??24} onChange={e=>set('ownershipMonths',+e.target.value)}/></label><label className="field">Uses per week<input type="number" min="0" value={v.usesPerWeek??0} onChange={e=>set('usesPerWeek',+e.target.value)}/></label><label className="field">Accessories<MI k="accessories"/></label><label className="field">Maintenance<MI k="maintenance"/></label><label className="field">Recurring costs<MI k="recurringOwnershipCosts"/></label><label className="field">Expected resale<MI k="expectedResaleValue"/></label></div>{r.ownership&&<div className="rows"><Row label="Total ownership cost" value={money(r.ownership.totalOwnershipCost)}/><Row label="Cost per month" value={money(r.ownership.costPerMonth)}/><Row label="Cost per expected use" value={money(r.ownership.costPerUse)}/></div>}</div></details></section><p className="resultDisclaimer">These are consequences of the numbers and boundaries you entered, not a recommendation to buy or not buy.</p></>}
 </main>;
}