'use client';
import {useMemo,useState} from 'react';
const fmt=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number.isFinite(n)?n:0);
const months=(n:number|null)=>n===null?'N/A':`${n.toFixed(1)} mo`;
function emi(p:number,rate:number,n:number){if(n<=0)return 0;if(rate===0)return p/n;const r=rate/1200;return p*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1)}
export default function AffordabilityApp(){
 const [v,setV]=useState({price:149900,income:140000,essentials:60000,debt:15000,emergency:300000,available:200000,target:6,mode:'cash',down:30000,term:12,rate:12,fees:2000,save:25000,wait:3,stress:2});
 const set=(k:string,x:number|string)=>setV(s=>({...s,[k]:x}));
 const r=useMemo(()=>{const obligations=v.essentials+v.debt,liquid=v.emergency+v.available,upfront=v.mode==='cash'?v.price:v.down+v.fees,newEmi=v.mode==='emi'?emi(Math.max(0,v.price-v.down),v.rate,v.term):0,fromAvailable=Math.min(upfront,v.available),remaining=upfront-fromAvailable,fromEmergency=Math.min(remaining,v.emergency),shortfall=Math.max(0,remaining-v.emergency),availableAfter=v.available-fromAvailable,emergencyAfter=v.emergency-fromEmergency,after=availableAfter+emergencyAfter,afterOb=obligations+newEmi,runway=obligations?liquid/obligations:null,runwayAfter=afterOb?after/afterOb:null,required=v.target*afterOb,gap=Math.max(0,required-after),free=v.income-obligations-newEmi,totalFinance=v.mode==='emi'?v.down+v.fees+newEmi*v.term:v.price;return{obligations,liquid,newEmi,shortfall,emergencyAfter,after,afterOb,runway,runwayAfter,required,gap,free,totalFinance,premium:totalFinance-v.price,waitAvailable:v.available+Math.max(0,v.save)*v.wait,stressAfter:Math.max(0,after-(v.essentials+v.debt+newEmi)*v.stress),maxPreserve:Math.max(0,liquid-v.target*obligations)}} ,[v]);
 const fact=r.shortfall>0?'Current liquid cash is insufficient.':r.emergencyAfter<v.emergency?'This purchase uses emergency savings.':'Funded without emergency savings.';
 return <main className="appShell"><nav className="nav"><div className="brand"><div className="brandMark">₹</div><div><b>BeforeYouBuy</b><small>Purchase impact simulator</small></div></div><div className="navActions"><button onClick={()=>localStorage.setItem('cai-scenario',JSON.stringify(v))}>Save on device</button><button onClick={()=>{const x=localStorage.getItem('cai-scenario');if(x)setV(JSON.parse(x))}}>Load</button></div></nav>
 <section className="hero"><div><div className="eyebrow">PRIVATE • LOCAL • DETERMINISTIC</div><h1>Can I afford it?</h1><p>See what a purchase changes in your savings, monthly flexibility and financial runway — without handing your financial data to a server.</p></div><div className="heroCard"><span>Sample purchase</span><strong>{fmt(v.price)}</strong><small>Change any number. Results update instantly.</small></div></section>
 <section className="workspace"><aside className="card inputPanel"><div className="sectionTitle"><span>01</span><h2>Your numbers</h2></div>{[['Purchase price','price'],['Monthly take-home','income'],['Essential monthly spend','essentials'],['Existing monthly debt','debt'],['Emergency savings','emergency'],['Available savings','available']].map(([l,k])=><label className="field" key={k}>{l}<input type="number" value={(v as any)[k]} onChange={e=>set(k,+e.target.value)}/></label>)}<label className="field">Reserve target: {v.target} months<input type="range" min="1" max="18" value={v.target} onChange={e=>set('target',+e.target.value)}/></label><div className="segmented"><button className={v.mode==='cash'?'active':''} onClick={()=>set('mode','cash')}>Cash</button><button className={v.mode==='emi'?'active':''} onClick={()=>set('mode','emi')}>EMI</button></div>{v.mode==='emi'&&<><div className="two"><label className="field">Down payment<input type="number" value={v.down} onChange={e=>set('down',+e.target.value)}/></label><label className="field">Fees<input type="number" value={v.fees} onChange={e=>set('fees',+e.target.value)}/></label></div><div className="two"><label className="field">Months<input type="number" value={v.term} onChange={e=>set('term',+e.target.value)}/></label><label className="field">Interest %<input type="number" value={v.rate} onChange={e=>set('rate',+e.target.value)}/></label></div></>}</aside>
 <div className="results"><section className="card resultHero"><div><div className="eyebrow">PURCHASE IMPACT</div><h2>{fact}</h2><p className="note">No score and no buy/don’t-buy verdict. These are consequences of the numbers you entered.</p></div><div className="status">{r.after>=r.required?'Reserve target preserved':'Below selected reserve target'}</div></section><div className="metricGrid">{[['Liquid savings after',fmt(r.after)],['Runway after',months(r.runwayAfter)],['Monthly free cash',fmt(r.free)],['Reserve gap',fmt(r.gap)]].map(([a,b])=><div className="card metric" key={a}><small>{a}</small><strong>{b}</strong></div>)}</div>
 <section className="card detail"><div className="sectionTitle"><span>02</span><h2>Before vs after</h2></div><div className="rows"><div><span>Total liquid savings</span><b>{fmt(r.liquid)} → {fmt(r.after)}</b></div><div><span>Liquid runway</span><b>{months(r.runway)} → {months(r.runwayAfter)}</b></div><div><span>Core monthly obligations</span><b>{fmt(r.obligations)} → {fmt(r.afterOb)}</b></div>{v.mode==='emi'&&<><div><span>New EMI</span><b>{fmt(r.newEmi)}/mo</b></div><div><span>Total financing cost</span><b>{fmt(r.totalFinance)} (+{fmt(r.premium)})</b></div></>}</div></section>
 <section className="card detail"><div className="sectionTitle"><span>03</span><h2>Wait simulator</h2></div><div className="two"><label className="field">Monthly purchase saving<input type="number" value={v.save} onChange={e=>set('save',+e.target.value)}/></label><label className="field">Wait: {v.wait} months<input type="range" min="0" max="24" value={v.wait} onChange={e=>set('wait',+e.target.value)}/></label></div><p>If you wait {v.wait} months and actually save {fmt(v.save)}/month, available savings become <b>{fmt(r.waitAvailable)}</b>.</p></section>
 <section className="card detail"><div className="sectionTitle"><span>04</span><h2>Breaking point & stress test</h2></div><div className="metricGrid"><div className="metric"><small>Cash while preserving your target</small><strong>{fmt(r.maxPreserve)}</strong></div><div className="metric"><small>After {v.stress}-month income interruption</small><strong>{fmt(r.stressAfter)}</strong></div></div><label className="field">Income interruption: {v.stress} months<input type="range" min="0" max="12" value={v.stress} onChange={e=>set('stress',+e.target.value)}/></label></section>
 <section className="card detail"><div className="sectionTitle"><span>05</span><h2>How it is calculated</h2></div><p className="note">Runway = liquid savings ÷ required monthly obligations. Cash purchases use available savings first, then emergency savings. EMI reserve calculations include the new EMI. Your selected reserve target is a constraint you chose — not financial advice.</p></section></div></section><footer>Your numbers stay in this browser. No account. No database.</footer></main>}
